image: python

stages:
- build
- test

before_script:
- pip install -e .[dev]

python36-lint:
  image: python:3.6
  stage: build
  script:
    - flake8 podcaststore_api --ignore=E501

python36:
  image: python:3.6
  stage: test
  script: pytest -vv -s --cov=podcaststore_api --cov-report=term tests/


python37:
  image: python:3.7-rc
  stage: test
  script: pytest -vv -s --cov=podcaststore_api --cov-report=term tests/
