version: '3.1'

# secrets override configuration

services:
  db:
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: podcast_api
  api:
    environment:
      DJANGO_DEBUG: 1
      DEBUG_LEVEL: "INFO"
      DB_NAME: podcast_api
      DB_USER: db_user
      DB_PW: db_pass
      DB_HOST: db
      DB_PORT: 5432
      CACHE_HOST: cache
      CACHE_PORT: 6379
      EMAIL_USE_TLS: 1
      EMAIL_HOST_USER: "email@user.com"
      EMAIL_HOST_PASSWORD: "email_password"
      GUNICORN_WORKERS: 4
      GUNICORN_HTTPS: ""
