FROM python:3.7-slim-buster

LABEL maintainer "viniarck@gmail.com"

RUN mkdir /app
COPY scripts/ /app/scripts
COPY podcaststore_site/ /app/podcaststore_site
COPY podcaststore_api/ /app/podcaststore_api
COPY setup.py \
     manage.py \
     /app/
WORKDIR /app
RUN pip install .
