# Generated by Django 2.2 on 2019-08-18 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import podcaststore_api.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(podcaststore_api.mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcaststore_api.Podcast')),
            ],
            options={
                'abstract': False,
            },
            bases=(podcaststore_api.mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcaststore_api.Track')),
            ],
            options={
                'abstract': False,
            },
            bases=(podcaststore_api.mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(choices=[('like', 'like'), ('love', 'love'), ('amazing', 'amazing'), ('dislike', 'dislike')], max_length=16)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcaststore_api.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(podcaststore_api.mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PodcastUser',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcaststore_api.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(podcaststore_api.mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcaststore_api.Track')),
            ],
            options={
                'abstract': False,
            },
            bases=(podcaststore_api.mixins.ValidateOnSaveMixin, models.Model),
        ),
    ]
